# Generated by Django 3.0.5 on 2020-04-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_discussion', '0003_use_user_model_from_social_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smart_discussion.Article'),
            preserve_default=False,
        ),
    ]
